services:
  - type: web
    name: study-buddy-backend
    env: docker
    plan: free
    region: singapore # Optional: chose a region or remove to let Render decide
    branch: main
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: study-buddy-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_HOST
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CHAT_MODEL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false

databases:
  - name: study-buddy-db
    plan: free
    databaseName: study_buddy
    user: study_buddy_user
